# Generated by Django 2.1.1 on 2019-11-12 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0004_auto_20190518_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlternateChordImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='alternate_chords/')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ImmageAsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='alternate_chords/')),
            ],
        ),
        migrations.AddField(
            model_name='chord',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='chords/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='confirm_email',
            field=models.EmailField(default='asd@lkj.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='gold_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='platinum_member',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(upload_to='songs/'),
        ),
        migrations.AddField(
            model_name='immageascomment',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Song.Song'),
        ),
        migrations.AddField(
            model_name='immageascomment',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Song.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Song.Song'),
        ),
        migrations.AddField(
            model_name='comment',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Song.Profile'),
        ),
        migrations.AddField(
            model_name='alternatechordimage',
            name='chord',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Song.Chord'),
        ),
    ]
