# Generated by Django 2.1.1 on 2019-11-12 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0005_auto_20191112_1537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImmageAsComment',
            new_name='ImageAsComment',
        ),
    ]
