# Generated by Django 2.2 on 2019-04-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('acronym', models.CharField(max_length=10)),
                ('image_file_path', models.FilePathField(path=None)),
                ('audio_file_path', models.FilePathField(path=None)),
            ],
        ),
        migrations.CreateModel(
            name='IsFavourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favourite', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('KI', 'Kiirtan'), ('PS', 'Prabhat Samgiita'), ('BH', 'Bhajan')], default='', max_length=30)),
                ('capo', models.PositiveIntegerField(null=True)),
                ('description', models.TextField()),
                ('written_by', models.CharField(max_length=50)),
                ('song_text', models.TextField()),
                ('audio_file_path', models.FilePathField(path=None)),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sanskrit_name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=25)),
                ('sign_up_date', models.DateField(auto_now_add=True)),
                ('edit_date', models.DateField(auto_now=True)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50, null=True)),
                ('photo', models.FilePathField(null=True, path=None)),
                ('liked_songs', models.ManyToManyField(through='Song.IsFavourite', to='Song.Song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='uploader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Song.User'),
        ),
        migrations.AddField(
            model_name='isfavourite',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Song.Song'),
        ),
        migrations.AddField(
            model_name='isfavourite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Song.User'),
        ),
        migrations.CreateModel(
            name='ChordProgression',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chord', models.ManyToManyField(to='Song.Chord')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Song.Song')),
            ],
        ),
    ]
