# Generated by Django 2.2 on 2019-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chordindex',
            name='index',
            field=models.IntegerField(default=0),
        ),
    ]
