# Generated by Django 2.2 on 2019-05-07 13:46

import Song.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chordindex',
            name='index',
            field=models.IntegerField(default=Song.models.ChordIndex.incrementalNumber),
        ),
    ]
