# Generated by Django 2.2 on 2019-05-05 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0002_auto_20190505_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_file_path',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
