# Generated by Django 2.2 on 2019-05-05 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0002_chordindex_index'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='chordindex',
            index_together={('song', 'index')},
        ),
    ]
