# Generated by Django 2.2 on 2019-04-14 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0002_auto_20190414_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='capo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='written_by',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='sanskrit_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
