# Generated by Django 2.2 on 2019-05-04 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0003_auto_20190501_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked_songs',
            field=models.ManyToManyField(null=True, through='Song.IsFavourite', to='Song.Song'),
        ),
    ]
