# Generated by Django 2.2 on 2019-05-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0003_auto_20190505_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
