# Generated by Django 2.2 on 2019-04-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0003_auto_20190414_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='type',
            field=models.CharField(choices=[('KI', 'Kiirtan'), ('PS', 'Prabhat Samgiita'), ('BH', 'Bhajan')], max_length=30),
        ),
    ]
