# Generated by Django 2.2 on 2019-05-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0003_auto_20190505_1815'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='chordindex',
            index_together={('song', 'index', 'chord')},
        ),
    ]
