# Generated by Django 2.2 on 2019-04-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0004_auto_20190425_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='first_name',
        ),
    ]
