# Generated by Django 2.2 on 2019-05-05 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0004_auto_20190505_1817'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='chordindex',
            index_together=set(),
        ),
    ]
