# Generated by Django 2.2 on 2019-04-29 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0005_auto_20190429_1407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='profile_photo',
        ),
    ]
