# Generated by Django 2.2 on 2019-05-04 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0006_auto_20190504_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isfavourite',
            name='is_favourite',
            field=models.BooleanField(null=True),
        ),
    ]
