# Generated by Django 2.2 on 2019-04-29 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0007_auto_20190429_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='isfavourite',
            old_name='user',
            new_name='profile',
        ),
    ]
