# Generated by Django 2.2 on 2019-05-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0008_auto_20190504_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='charfield',
            field=models.CharField(default='', max_length=50),
        ),
    ]
