# Generated by Django 2.2 on 2019-05-01 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0008_auto_20190429_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sanskrit_name',
        ),
    ]
