# Generated by Django 2.2 on 2019-05-04 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Song', '0009_song_charfield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chordprogression',
            name='song',
        ),
        migrations.RemoveField(
            model_name='song',
            name='charfield',
        ),
        migrations.AddField(
            model_name='song',
            name='chord_progression',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Song.ChordProgression'),
            preserve_default=False,
        ),
    ]
